version: '3.8'

services:
  backend:
    build:
      context: ./todoproject
      dockerfile: Dockerfile
    container_name: todo-backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db

  frontend:
    build:
      context: ./todoapp
      dockerfile: Dockerfile
    container_name: todo-frontend
    ports:
      - "3000:80"

  db:
    image: postgres:13
    container_name: todo-db
    environment:
      POSTGRES_USER: arif
      POSTGRES_PASSWORD: arif
      POSTGRES_DB: todo_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: